using OneOf;

namespace WD.Botifier.BotRegistry.Application.RedditBots.AddBotUserNameMentionInCommentTrigger;

[GenerateOneOf]
public partial class AddBotUserNameMentionInCommentTriggerCommandResult : OneOfBase<AddBotUserNameMentionInCommentTriggerCommandSuccessResult, AddBotUserNameMentionInCommentTriggerCommandBotNotFoundResult>
{
}

public class AddBotUserNameMentionInCommentTriggerCommandSuccessResult
{
}

public class AddBotUserNameMentionInCommentTriggerCommandBotNotFoundResult
{
}